### ISSUE TITLE
PHP Highlighter interprets '#' as beginning a comment, even if its in a string.

### ISSUE THREAD

**Issue by milesblackwood** [LeaVerou/prism#487]
Totally valid PHP is being mis-highlighted by Prism.js. Instead of treating any characters inside single quotes as part of that string, the '#' hash symbol is turning a line into a comment. Here's a trivial example:
![screen shot 2015-01-28 at 12 12 28 pm](https://cloud.githubusercontent.com/assets/1195879/5942774/b225c1ba-a6e7-11e4-9c5b-46ed46be93b6.png)

**Comment by Golmote** [comment]
Yes, this is a known issue.
PHP supports [shell-like comments](http://php.net/manual/en/language.basic-syntax.comments.php) starting with an hash, and Prism does not handle properly comment-like substrings. So this includes any string containing an hash...

It might be a good thing, though, to handle shell-like comments after the strings, because I think strings containing hashes are more common than shell-like comments containing two quotes of the same type.

@milesj what do you think?

**Comment by milesj** [comment]
The other issue I believe is that the comment pattern is ran before the string pattern.

**Comment by Golmote** [comment]
@milesj Yes, that's my point...
I was suggesting we should run the "classic" comment pattern first (`//` and `/* */`), then the string pattern, and then the shell-like pattern.
(Or maybe multi-line comments first, then strings and then single-line comments (both styles))

Sorry if it wasn't clear ^^

**Comment by milesj** [comment]
Ah yeah, that makes more sense. That would solve the issue I believe.

**Comment by milesblackwood** [comment]
I was just looking at the /components/prism-php.js

The comment pattern gets run all at once: (lines 17 thru 20)

```
	'comment': {
		pattern: /(^|[^\\])(\/\*[\w\W]*?\*\/|(^|[^:])(\/\/|#).*?(\r?\n|$))/g,
		lookbehind: true
	}
```

This is the particular capture group causing the issue: `(\/\/|#).*?`

We are using prism for an internal knowledge-sharing library at my job, so we simply changed that to remove the OR and hash, resulting in `(\/\/).*?`. (which if I understand correctly looks for two literal forward slashes, then any number of characters.)

I don't know much about prism.js, but where would this pattern get moved to match *after* the string matching pattern has run?

**Comment by milesj** [comment]
You would have to add a new matching pattern after the string declaration that only matches `#`.
```
    'comment_hash': {
        pattern: /.../g,
        lookbehind: true
    }
```

**Comment by Golmote** [comment]
Please see 00955466fd0da55ddedb1d997574dbd051d2ee34 for details.

With that change, we get the following results:

![prism-php](https://cloud.githubusercontent.com/assets/565460/5953550/b8aef94e-a78b-11e4-9b82-4c30b235374a.png)

I hope this will handle better the most common use cases.

@milesblackwood Can you update your version of Prism and confirm the issue is fixed?

**Comment by milesj** [comment]
Yeah, not much we can do about those 2 bottom issues without a true lexer. Looks good to me.
